apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpassword"
  MYSQL_DATABASE: "phishingdb"
  MYSQL_USER: "phishuser"
  MYSQL_PASSWORD: "phishpassword"